spring.application.name=sentinel-core-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/my_app_db
spring.datasource.username=postgres
spring.datasource.password=post
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true